### ISSUE TITLE
Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage

### ISSUE THREAD

**Issue by olivier-duval** [matomo-org/matomo-sdk-android#258]
As of Android O, if StrictMode is enabled with VmPolicy detectAll(), an untagged socket violation is thrown:

E/StrictMode: null
    java.lang.Throwable: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2021)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:78)
        at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:47)
        at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:310)
        at libcore.io.IoBridge.socket(IoBridge.java:667)
        at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:116)
        at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:107)
        at java.net.Socket.createImpl(Socket.java:484)
        at java.net.Socket.getImpl(Socket.java:547)
        at java.net.Socket.setSoTimeout(Socket.java:1175)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
        at org.matomo.sdk.dispatcher.DefaultPacketSender.send(DefaultPacketSender.java:78)
        at org.matomo.sdk.dispatcher.DefaultDispatcher$1.run(DefaultDispatcher.java:179)
        at java.lang.Thread.run(Thread.java:764)

This problem is related to okhttp (included by matomo)
As mentioned in this OkHTTP issue https://github.com/square/okhttp/issues/3537, there will be no fix in OkHTTP...

The fix is quite simple: TrafficStats.setThreadStatsTag(1); must be called in each new thread that will use URLConnection. So a good place would be at the beginning of in the "run" method in "DefaultDispatcher.java"

**Comment by olivier-duval** [comment]
I found a workaround, until it's corrected: at the beginning of the app, I use:

Matomo lMatomo = Matomo.getInstance(getApplicationContext());
		lMatomo.setDispatcherFactory(new DispatcherFactory() {
			@Override
			public Dispatcher build(Tracker tracker) {
				return new DefaultDispatcher(
						new EventCache(new EventDiskCache(tracker)),
						new Connectivity(tracker.getMatomo().getContext()),
						new PacketFactory(tracker.getAPIUrl()),
						new DefaultPacketSender() {
							boolean mSetThreadStatsTag = false;

							@Override
							public boolean send(Packet packet) {
								if (!mSetThreadStatsTag) {
									TrafficStats.setThreadStatsTag(1);
									mSetThreadStatsTag = true;
									L.i("mSetThreadStatsTag set");
								}
								return super.send(packet);
							}
						});
			}
		});
		mTracker = TrackerBuilder.createDefault("https://xxxxxxxxxx/matomo.php", 2).build(lMatomo);

It's only a hack... but it works  ;-)

**Comment by d4rken** [comment]
Wouldn't it make more sense to disable this `VmPolicy` as just tagging everything with `1` basically means that you are not interested in tagging the sockets correctly, so why enable the penalty for it at all?

An actual fix would be to choose a "unique" tag for all Matomo traffic and allowing for to set a custom tag. 

Should the tags be different per tracker too? :thinking: really depends on what one tries to monitor...

**Comment by olivier-duval** [comment]
You're right: it would be better to be able to set this tag to any "unique" chosen value, for people interested in tracking this.

However, my use case is more "simple": I'm in the process of debugging so I enabled "detectAll()" to catch... well... anything (unclosed cursor and that kind of stuff). I use okhttp too so I may trigger some problems in my own code.
The code is for each thread. Might be the same or not (for example, a thread pool might share the same code)
For now, I'm more interested by "cleaning logs" than by the information returned. That's why I used 1
